import React from 'react'
import "../../styles/training.css";

const trainingData = [
  {
    icon: "ri-microsoft-fill",
    desc: "Teachers don't get too much workload"

  },
  {
    icon: "ri-checkbox-multiple-fill",
    desc: 'The Assignments are graded by the AI'

  },
  {
    icon: "ri-group-fill",
    desc: 'Custom Learning path can be generated by the Result'

  },

]

const About = () => {
  return <section id="about">
    <div className="container">
        <div className="training__wrapper">
            <div className="training__content">
            <h6 className='subtitle'>Assignment Assistance</h6>
            {
            trainingData.map((item,index)=>(
                <div className="training__item" key = {index}>
                <span className="training__icon">
                <i class={item.icon}></i>
                
                </span>
                <h3 className="training__description">{item.desc}</h3>
                
            </div>
            ))
           }
            </div>

            <div className="training__img"></div>
        </div>
    </div>
  </section>
}

export default About
